#!/bin/sh

sudo docker run -it -d \
    -v inspircd/conf:/home/irc/inspircd/conf \
    -v inspircd/cert:/home/irc/inspircd/cert \
    -v anope/conf:/home/irc/services/conf \
    -v anope/logs:/home/irc/services/logs \
    -v inspircd/logs:/home/irc/inspircd/logs \
    -p 6697:6697 \
    --name ircanope \
    --hostname ircanope \
    ircanope
